add a topographyappliance checker skeleton
ZEISS/czicheck pull request #10
Opened 2024-04-30 14:50 UTC by m-aXimilian

# STOP - Read this First!
Reporting a security vulnerability?  
Check out the project's [security policy](https://github.com/zeiss/czicheck/security/policy).

# Fill out and Adjust this Template

## Description

Summary of the change(s) and which issue(s) is/are fixed  
Relevant motivation and context  
Dependencies required for this change  

Fixes # (issue)

### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe the tests that you ran to verify your changes.  
Provide instructions to reproduce.

## Checklist:

- [ ] I followed the Contributing Guidelines.
- [ ] I did a self-review.
- [ ] I commented my code, particularly in hard-to-understand areas.
- [ ] I updated the documentation.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

2024-05-03 11:06 UTC, ptahmose commented on CZICheck/checkers/checkerTopographyApplianceValidation.cpp
> +        finding.severity = CResultGatherer::Severity::Fatal;
not sure - I mean, I'd reckon it is not an error if the appliance-node is not present, or is it?

2024-05-03 11:07 UTC, ptahmose commented on CZICheck/checkers/checkerTopographyApplianceValidation.cpp
> +void CCheckTopgraphyApplianceMetadata::CheckTopographySectionExisting(const std::shared_ptr<libCZI::ICziMetadata> czi_metadata)
should be a const reference I guess
const std::shared_ptr<libCZI::ICziMetadata>& czi_metadata

2024-05-03 11:13 UTC, ptahmose commented on CZICheck/checkers/checkerTopographyApplianceValidation.h
> +    const char* kTopographyItemId = "Topography:1";
consider making this static - I'd think either 
`static const char* kTopographyItemId;`
and define the variable in the cpp-file,

or use C++11's constexpr

` static constexpr const char* kTopographyItemId = "Topography:1";`

2024-05-03 11:21 UTC, ptahmose commented on CZICheck/checkers/checkerTopographyApplianceValidation.cpp
> +        finding.severity = CResultGatherer::Severity::Fatal;
Reading through https://github.com/ZEISS/czicheck/blob/main/documentation/architecture.md I'd think - there shouldn't be any report at all. "Info" is defined "something unusual", and I'd not see it "unusual" if no Appliances-node is present (or, if it doesn't contain Topography-data).

2024-05-03 11:25 UTC, ptahmose commented on CZICheck/checkers/checkerTopographyApplianceValidation.cpp
> +    const auto metadata_segment = this->GetCziMetadataAndReportErrors(CCheckTopgraphyApplianceMetadata::kCheckType);
be aware that [GetCziMetadataAndReportErrors](https://github.com/ZEISS/czicheck/blob/b00354bffd3a771987e34f0cea3298fd916fc0a1/CZICheck/checkers/checkerbase.h#L31C4-L38C82) **may** report null (and we shouldn't crash then).

2024-05-08 11:26 UTC, ptahmose commented on CZICheck/checkers/checkerTopographyApplianceValidation.cpp
> +        [this, &heightmaps, &textures, &enumChildrenLabmda](std::shared_ptr<libCZI::IXmlNodeRead> xmlnode) -> bool
could/should read 
`const std::shared_ptr<libCZI::IXmlNodeRead>&`
I reckon

2024-05-08 11:29 UTC, ptahmose commented on CZICheck/checkers/checkerTopographyApplianceValidation.cpp
> +        catch (invalid_argument)
prefer catching a const reference

2024-05-08 11:30 UTC, ptahmose commented on CZICheck/checkers/checkerTopographyApplianceValidation.cpp
> +        DimensionView* config = &configurations.at(dim);
why a pointer - wouldn't a const reference work here?

2024-05-08 11:32 UTC, ptahmose commented on CZICheck/checkers/checkerTopographyApplianceValidation.h
> +        // a Size is not neccessarily needed iot be valid here!
Is "iot" a commonly used abbreviation? If so - fine, I'll try to learn it, otherwise better spell it out - I assume it means "in order to"?

2024-05-08 11:33 UTC, ptahmose commented on CZICheck/checkers/checkerTopographyApplianceValidation.h
> +            return true;
I'd recommend - always have curly braces

2024-05-08 21:40 UTC, ptahmose approved these changes
LGTM

2024-05-08 21:49 UTC, ptahmose approved these changes

2024-05-08 23:11 UTC, ptahmose requested changes
...we forgot the bump the version number (check CMakeLists.txt in repo's root folder, line 8). I'd guess - this change adds a new feature, so the minor-version-number should be incremented -> "0.2.0". And please add an entry to documentation/version-history.md.

2024-05-09 10:28 UTC, m-aXimilian commented
@ptahmose Thank you very much for fixing all the typos and ugliness!! Very much appreciated! I updated the version number and the version history according to your comment.

2024-05-09 21:44 UTC, ptahmose approved these changes
LGTM, thanks!

2024-05-09 21:46 UTC, merged